### ISSUE TITLE
tokio runtime coredump

### ISSUE THREAD

**Issue by cppcoffee** [tokio-rs/tokio#5974]
**Version**

```shell
# cargo tree | grep tokio
host v0.1.0 (/root/tokio-dylib/host)
└── tokio v1.32.0
    └── tokio-macros v2.1.0 (proc-macro)
plugin v0.1.0 (/root/tokio-dylib/plugin)
└── tokio v1.32.0 (*)
```

**Platform**

```
# uname -a
Linux localhost 4.15.0-213-generic #224-Ubuntu SMP Mon Jun 19 13:30:12 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

**Description**
Pass to `extern "C" foo(*const Handle)` using `tokio::runtime::Handle::current()`, run `handle.spawn` coredump.

I tried this code:

https://github.com/cppcoffee/tokio-dylib

```shell
# cargo run
start plugin
end plugin
end host
Segmentation fault (core dumped)
```

**Comment by taiki-e** [comment]
As explained in the issue mentioned in the previous issue, such usage is not supported. There are no guarantees about the layout of the internal types, so your usage is unsound.

**Comment by taiki-e** [comment]
By the way, if you want to do such a thing, a sound way is to use separate instances of runtime for the plugin and loader sides. The async functions themselves are not ffi-safe, so you either need to use a library like async-ffi (note: I have not reviewed the soundness of its implementation) or combine block_on on the plugin side and spawn_blocking on the loader side.

**Comment by cppcoffee** [comment]
Can this be solved by compiling tokio to .so and then loading libtokio.so for both plugin.so and main?

**Comment by cppcoffee** [comment]
Is the problem that ffi `extern "C"` (plugin.so) has a different memory layout than bin (host loader), which is causing the tokio `Handle` structure field error?

**Comment by cppcoffee** [comment]
> combine block_on on the plugin side and spawn_blocking on the loader side.

Want to use tokio runtime in plugin.so `extern "C" foo()` function implementation, any suggestions?

**Comment by taiki-e** [comment]
> Can this be solved by compiling tokio to .so and then loading libtokio.so for both plugin.so and main?

> Want to use tokio runtime in plugin.so extern "C" foo() function implementation, any suggestions?

Please see the previous discussion linked; it has already been explained that the first does not resolve the issue, nor is there a known reasonable/sound way to handle the second without using separate runtimes.
